bash "add_include_directive" do
  cwd "/home/#{node['go']['user']}"
  user node['go']['user']
  group node['go']['user']
  code <<-EOH
    cat << 'EOF' >> /home/#{node['go']['user']}/.bashrc
    # Generated by Chef add_include_directive
    for i in #{node['go']['shell_d']}/*.sh; do
      if [ -r "$i" ]; then
        if [ "$PS1" ]; then
          . "$i"
        else
          . "$i" >/dev/null 2>&1
        fi
      fi
    done
  EOH
  not_if "grep 'Generated by Chef add_include_directive' /home/#{node['go']['user']}/.bashrc"
end